contry_groups:
  nordic: ['NO','SE','FI','DK','GB','IE']
  central: ['DE','AT','LU','BE','NL','CZ']
  eastern: ['PL','LT','LV','EE','RO','SK','HU']
  west: ['PT','ES','FR']
  south: ['IT','CH','SI','GR','HR','RS','AL','ME','BA','MK','BG']

variables:
  x1:
    1: 'Generator'
    2: ['onwind','offwind-ac','offwind-dc']
    3: 'p_nom'
    4: 'nordic'
  x2: 
    1: 'Generator'
    2: ['onwind','offwind-ac','offwind-dc']
    3: 'p_nom'
    4: 'central'
  x3: 
    1: 'Generator'
    2: ['onwind','offwind-ac','offwind-dc']
    3: 'p_nom'
    4: 'eastern'
  x4: 
    1: 'Generator'
    2: ['onwind','offwind-ac','offwind-dc']
    3: 'p_nom'
    4: 'west'
  x5: 
    1: 'Generator'
    2: ['onwind','offwind-ac','offwind-dc']
    3: 'p_nom'
    4: 'south'

  x6: 
    1: 'Generator'
    2: ['solar']
    3: 'p_nom'
    4: 'nordic'
  x7: 
    1: 'Generator'
    2: ['solar']
    3: 'p_nom'
    4: 'central'
  x8: 
    1: 'Generator'
    2: ['solar']
    3: 'p_nom'
    4: 'eastern'
  x9: 
    1: 'Generator'
    2: ['solar']
    3: 'p_nom'
    4: 'west'
  x10: 
    1: 'Generator'
    2: ['solar']
    3: 'p_nom'
    4: 'south'
  

solving:
  tmpdir: 'scratch/$SLURM_JOB_ID' #'scratch/'
  #$SLURM_JOBID/
  #"/home/marta/tmp/" 
  
  
  options:
    formulation: kirchhoff
    #clip_p_max_pu: 1.e-2
    load_shedding: false
    noisy_costs: false

    min_iterations: 1
    max_iterations: 1
    # nhours: 1

  solver:
    name: gurobi
    threads: 2
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-6
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    LogToConsole: 0
    FeasibilityTol: 1.e-6

    #name: cplex
    #threads: 4
    #lpmethod: 4 # barrier
    #solutiontype: 2 # non basic solution, ie no crossover
    # barrier_convergetol: 1.e-5
    # feasopt_tolerance: 1.e-6
  mem: 100000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2

